#define NBR_INTERFACES        7
#define NBR_APPRENANTS        24
#define NBR_FORMATIONS        72
#define NBR_CENTRES_FORMATION 5
#define NBR_SPECIALITES       5
#define NBR_NODES 	      NBR_CENTRES_FORMATION + NBR_INTERFACES + NBR_APPRENANTS
                  
/* code des compétence en langage des signes et en codage LPC */
#define COMPETENCE_SIGNES     0
#define COMPETENCE_CODAGE     1
                  
/* competences des interfaces en SIGNES et CODAGE*/
int competences_interfaces[NBR_INTERFACES][2]={
    {1,0}, /* compétence en langages des SIGNES mais pas en CODAGE LPC */
    {0,1}, /* pas de compétence en langages des SIGNES mais compétence en CODAGE LPC */
    {0,1},
    {1,0},
    {0,1},
    {0,1},
    {0,1}
};
                  
/* spécialités des interfaces */
#define SPECIALITE_SANS       -1 /* Enseigné dans le centre le plus proche */
#define SPECIALITE_MENUISERIE 0
#define SPECIALITE_ELECTRICITE 1
#define SPECIALITE_MECANIQUE 2
#define SPECIALITE_INFORMATIQUE 3
#define SPECIALITE_CUISINE 4
                  
/* specialite des interfaces */
int specialite_interfaces[NBR_INTERFACES][NBR_SPECIALITES]={
    {0,0,0,1,0},
    {0,0,1,0,0},
    {0,0,0,1,0},
    {0,1,0,0,0},
    {0,1,0,1,0},
    {0,1,0,0,0},
    {0,0,0,0,0}
};
                  
/* coordonnées des centres de formation, des interfaces et des apprenants */
float coord[NBR_NODES][2]={
                  
    /* Les interfaces se rendent du centre SESSAD à l'école de formation */
    {180,188}, /* centre 0 */
                  
    /* Centres de formation */
    {36,120}, /* ecole formation SPECIALITE_MENUISERIE */
    {161,173}, /* ecole formation SPECIALITE_ELECTRICITE */
    {60,46}, /* ecole formation SPECIALITE_MECANIQUE */
    {79,93}, /* ecole formation SPECIALITE_INFORMATIQUE */
    {2,156}, /* ecole formation SPECIALITE_CUISINE */
                  
    /* Apprenants */
    {38,174}, /* apprenant 0 */
    {148,166}, /* apprenant 1 */
    {38,67}, /* apprenant 2 */
    {146,124}, /* apprenant 3 */
    {69,130}, /* apprenant 4 */
    {47,102}, /* apprenant 5 */
    {194,183}, /* apprenant 6 */
    {30,17}, /* apprenant 7 */
    {53,136}, /* apprenant 8 */
    {104,193}, /* apprenant 9 */
    {38,99}, /* apprenant 10 */
    {17,160}, /* apprenant 11 */
    {167,123}, /* apprenant 12 */
    {152,42}, /* apprenant 13 */
    {181,168}, /* apprenant 14 */
    {4,94}, /* apprenant 15 */
    {45,155}, /* apprenant 16 */
    {19,195}, /* apprenant 17 */
    {162,154}, /* apprenant 18 */
    {91,67}, /* apprenant 19 */
    {141,35}, /* apprenant 20 */
    {25,192}, /* apprenant 21 */
    {160,12}, /* apprenant 22 */
    {69,129}/* apprenant 23 */
};
                  
#define NBR_FORMATIONS          72
                  
#define LUNDI                  1
#define MARDI                  2
#define MERCREDI               3
#define JEUDI                  4
#define VENDREDI               5
#define SAMEDI                 6
                  
/* formation : id formation, specialite ou centre de formation, competence, horaire debut formation, horaire fin formation */
int formation[NBR_FORMATIONS][6]={
   {0,SPECIALITE_INFORMATIQUE,COMPETENCE_SIGNES,SAMEDI,14,19},
   {0,SPECIALITE_MECANIQUE,COMPETENCE_CODAGE,VENDREDI,13,19},
   {0,SPECIALITE_ELECTRICITE,COMPETENCE_CODAGE,VENDREDI,9,11},
   {1,SPECIALITE_INFORMATIQUE,COMPETENCE_SIGNES,SAMEDI,16,19},
   {1,SPECIALITE_MECANIQUE,COMPETENCE_SIGNES,MERCREDI,10,12},
   {1,SPECIALITE_CUISINE,COMPETENCE_SIGNES,MARDI,8,12},
   {2,SPECIALITE_MENUISERIE,COMPETENCE_SIGNES,LUNDI,13,18},
   {2,SPECIALITE_CUISINE,COMPETENCE_SIGNES,MARDI,14,16},
   {2,SPECIALITE_CUISINE,COMPETENCE_CODAGE,LUNDI,9,11},
   {3,SPECIALITE_INFORMATIQUE,COMPETENCE_CODAGE,MARDI,8,10},
   {3,SPECIALITE_MECANIQUE,COMPETENCE_CODAGE,LUNDI,13,16},
   {3,SPECIALITE_MENUISERIE,COMPETENCE_SIGNES,MARDI,14,16},
   {4,SPECIALITE_MENUISERIE,COMPETENCE_CODAGE,LUNDI,16,19},
   {4,SPECIALITE_ELECTRICITE,COMPETENCE_CODAGE,SAMEDI,14,19},
   {4,SPECIALITE_CUISINE,COMPETENCE_CODAGE,MARDI,16,18},
   {5,SPECIALITE_CUISINE,COMPETENCE_SIGNES,MERCREDI,15,18},
   {5,SPECIALITE_INFORMATIQUE,COMPETENCE_CODAGE,JEUDI,13,19},
   {5,SPECIALITE_CUISINE,COMPETENCE_SIGNES,SAMEDI,14,18},
   {6,SPECIALITE_INFORMATIQUE,COMPETENCE_CODAGE,JEUDI,8,11},
   {6,SPECIALITE_MECANIQUE,COMPETENCE_CODAGE,VENDREDI,13,18},
   {6,SPECIALITE_INFORMATIQUE,COMPETENCE_SIGNES,MERCREDI,16,18},
   {7,SPECIALITE_MECANIQUE,COMPETENCE_SIGNES,MERCREDI,16,19},
   {7,SPECIALITE_MENUISERIE,COMPETENCE_SIGNES,MERCREDI,8,12},
   {7,SPECIALITE_MECANIQUE,COMPETENCE_SIGNES,SAMEDI,10,12},
   {8,SPECIALITE_MENUISERIE,COMPETENCE_CODAGE,VENDREDI,8,12},
   {8,SPECIALITE_MENUISERIE,COMPETENCE_SIGNES,SAMEDI,16,18},
   {8,SPECIALITE_MECANIQUE,COMPETENCE_SIGNES,JEUDI,10,12},
   {9,SPECIALITE_MENUISERIE,COMPETENCE_SIGNES,JEUDI,10,12},
   {9,SPECIALITE_CUISINE,COMPETENCE_CODAGE,JEUDI,16,18},
   {9,SPECIALITE_INFORMATIQUE,COMPETENCE_CODAGE,JEUDI,16,19},
   {10,SPECIALITE_MECANIQUE,COMPETENCE_SIGNES,MARDI,15,19},
   {10,SPECIALITE_CUISINE,COMPETENCE_SIGNES,SAMEDI,14,17},
   {10,SPECIALITE_INFORMATIQUE,COMPETENCE_SIGNES,JEUDI,15,19},
   {11,SPECIALITE_CUISINE,COMPETENCE_CODAGE,LUNDI,10,12},
   {11,SPECIALITE_CUISINE,COMPETENCE_CODAGE,VENDREDI,8,11},
   {11,SPECIALITE_CUISINE,COMPETENCE_SIGNES,JEUDI,13,15},
   {12,SPECIALITE_ELECTRICITE,COMPETENCE_CODAGE,LUNDI,8,11},
   {12,SPECIALITE_MECANIQUE,COMPETENCE_CODAGE,SAMEDI,9,12},
   {12,SPECIALITE_MENUISERIE,COMPETENCE_SIGNES,MERCREDI,8,11},
   {13,SPECIALITE_INFORMATIQUE,COMPETENCE_SIGNES,JEUDI,15,19},
   {13,SPECIALITE_ELECTRICITE,COMPETENCE_SIGNES,LUNDI,16,18},
   {13,SPECIALITE_INFORMATIQUE,COMPETENCE_CODAGE,MERCREDI,8,10},
   {14,SPECIALITE_MENUISERIE,COMPETENCE_CODAGE,LUNDI,9,11},
   {14,SPECIALITE_ELECTRICITE,COMPETENCE_CODAGE,JEUDI,9,12},
   {14,SPECIALITE_MECANIQUE,COMPETENCE_SIGNES,LUNDI,8,12},
   {15,SPECIALITE_ELECTRICITE,COMPETENCE_CODAGE,MERCREDI,9,11},
   {15,SPECIALITE_MENUISERIE,COMPETENCE_SIGNES,VENDREDI,8,11},
   {15,SPECIALITE_INFORMATIQUE,COMPETENCE_SIGNES,MERCREDI,8,11},
   {16,SPECIALITE_CUISINE,COMPETENCE_SIGNES,MERCREDI,16,19},
   {16,SPECIALITE_ELECTRICITE,COMPETENCE_SIGNES,MARDI,9,12},
   {16,SPECIALITE_MECANIQUE,COMPETENCE_SIGNES,SAMEDI,16,19},
   {17,SPECIALITE_INFORMATIQUE,COMPETENCE_CODAGE,JEUDI,10,12},
   {17,SPECIALITE_MENUISERIE,COMPETENCE_SIGNES,MARDI,9,12},
   {17,SPECIALITE_MECANIQUE,COMPETENCE_SIGNES,MARDI,9,12},
   {18,SPECIALITE_INFORMATIQUE,COMPETENCE_CODAGE,MERCREDI,14,16},
   {18,SPECIALITE_MENUISERIE,COMPETENCE_SIGNES,MARDI,15,18},
   {18,SPECIALITE_INFORMATIQUE,COMPETENCE_CODAGE,VENDREDI,14,17},
   {19,SPECIALITE_MECANIQUE,COMPETENCE_SIGNES,LUNDI,8,11},
   {19,SPECIALITE_INFORMATIQUE,COMPETENCE_SIGNES,VENDREDI,14,19},
   {19,SPECIALITE_MENUISERIE,COMPETENCE_CODAGE,SAMEDI,16,18},
   {20,SPECIALITE_MECANIQUE,COMPETENCE_CODAGE,SAMEDI,15,18},
   {20,SPECIALITE_CUISINE,COMPETENCE_SIGNES,LUNDI,8,12},
   {20,SPECIALITE_ELECTRICITE,COMPETENCE_CODAGE,MERCREDI,15,18},
   {21,SPECIALITE_INFORMATIQUE,COMPETENCE_CODAGE,MARDI,16,19},
   {21,SPECIALITE_MENUISERIE,COMPETENCE_SIGNES,MERCREDI,14,18},
   {21,SPECIALITE_INFORMATIQUE,COMPETENCE_SIGNES,MERCREDI,8,10},
   {22,SPECIALITE_MENUISERIE,COMPETENCE_CODAGE,JEUDI,15,19},
   {22,SPECIALITE_INFORMATIQUE,COMPETENCE_CODAGE,JEUDI,10,12},
   {22,SPECIALITE_CUISINE,COMPETENCE_CODAGE,LUNDI,15,18},
   {23,SPECIALITE_MECANIQUE,COMPETENCE_CODAGE,SAMEDI,9,11},
   {23,SPECIALITE_MENUISERIE,COMPETENCE_SIGNES,LUNDI,14,19},
   {23,SPECIALITE_MECANIQUE,COMPETENCE_CODAGE,MERCREDI,10,12}
};
                  
// EOF
