#define NBR_INTERFACES        15
#define NBR_APPRENANTS        32
#define NBR_FORMATIONS        96
#define NBR_CENTRES_FORMATION 5
#define NBR_SPECIALITES       5
#define NBR_NODES 	      NBR_CENTRES_FORMATION + NBR_INTERFACES + NBR_APPRENANTS
                  
/* code des compétence en langage des signes et en codage LPC */
#define COMPETENCE_SIGNES     0
#define COMPETENCE_CODAGE     1
                  
/* competences des interfaces en SIGNES et CODAGE*/
int competences_interfaces[NBR_INTERFACES][2]={
    {1,0}, /* compétence en langages des SIGNES mais pas en CODAGE LPC */
    {0,1}, /* pas de compétence en langages des SIGNES mais compétence en CODAGE LPC */
    {0,1},
    {0,1},
    {1,0},
    {0,1},
    {1,0},
    {1,0},
    {0,1},
    {1,0},
    {1,0},
    {0,1},
    {0,1},
    {0,1},
    {1,0}
};
                  
/* spécialités des interfaces */
#define SPECIALITE_SANS       -1 /* Enseigné dans le centre le plus proche */
#define SPECIALITE_MENUISERIE 0
#define SPECIALITE_ELECTRICITE 1
#define SPECIALITE_MECANIQUE 2
#define SPECIALITE_INFORMATIQUE 3
#define SPECIALITE_CUISINE 4
                  
/* specialite des interfaces */
int specialite_interfaces[NBR_INTERFACES][NBR_SPECIALITES]={
    {0,0,0,0,0},
    {0,0,0,0,0},
    {0,0,1,0,0},
    {0,0,0,0,1},
    {1,1,0,1,0},
    {0,0,1,0,0},
    {0,1,0,0,0},
    {0,0,0,0,0},
    {0,0,0,0,0},
    {1,0,0,0,0},
    {0,1,0,0,0},
    {0,0,1,0,0},
    {0,0,0,1,0},
    {0,0,0,0,1},
    {0,0,0,0,0}
};
                  
/* coordonnées des centres de formation, des interfaces et des apprenants */
float coord[NBR_NODES][2]={
                  
    /* Les interfaces se rendent du centre SESSAD à l'école de formation */
    {101,175}, /* centre 0 */
                  
    /* Centres de formation */
    {167,49}, /* ecole formation SPECIALITE_MENUISERIE */
    {83,84}, /* ecole formation SPECIALITE_ELECTRICITE */
    {133,190}, /* ecole formation SPECIALITE_MECANIQUE */
    {101,59}, /* ecole formation SPECIALITE_INFORMATIQUE */
    {115,25}, /* ecole formation SPECIALITE_CUISINE */
                  
    /* Apprenants */
    {60,117}, /* apprenant 0 */
    {151,80}, /* apprenant 1 */
    {78,7}, /* apprenant 2 */
    {74,33}, /* apprenant 3 */
    {44,141}, /* apprenant 4 */
    {174,57}, /* apprenant 5 */
    {96,190}, /* apprenant 6 */
    {30,16}, /* apprenant 7 */
    {156,116}, /* apprenant 8 */
    {59,76}, /* apprenant 9 */
    {133,72}, /* apprenant 10 */
    {18,177}, /* apprenant 11 */
    {112,74}, /* apprenant 12 */
    {78,14}, /* apprenant 13 */
    {199,17}, /* apprenant 14 */
    {29,17}, /* apprenant 15 */
    {41,41}, /* apprenant 16 */
    {27,20}, /* apprenant 17 */
    {70,41}, /* apprenant 18 */
    {100,87}, /* apprenant 19 */
    {127,169}, /* apprenant 20 */
    {149,115}, /* apprenant 21 */
    {13,90}, /* apprenant 22 */
    {19,10}, /* apprenant 23 */
    {180,172}, /* apprenant 24 */
    {43,122}, /* apprenant 25 */
    {140,83}, /* apprenant 26 */
    {132,157}, /* apprenant 27 */
    {86,42}, /* apprenant 28 */
    {165,59}, /* apprenant 29 */
    {57,5}, /* apprenant 30 */
    {8,36}/* apprenant 31 */
};
                  
#define NBR_FORMATIONS          96
                  
#define LUNDI                  1
#define MARDI                  2
#define MERCREDI               3
#define JEUDI                  4
#define VENDREDI               5
#define SAMEDI                 6
                  
/* formation : id formation, specialite ou centre de formation, competence, horaire debut formation, horaire fin formation */
int formation[NBR_FORMATIONS][6]={
   {0,SPECIALITE_INFORMATIQUE,COMPETENCE_SIGNES,JEUDI,16,18},
   {0,SPECIALITE_CUISINE,COMPETENCE_SIGNES,JEUDI,8,12},
   {0,SPECIALITE_MENUISERIE,COMPETENCE_CODAGE,LUNDI,15,17},
   {1,SPECIALITE_MENUISERIE,COMPETENCE_CODAGE,MERCREDI,14,19},
   {1,SPECIALITE_MECANIQUE,COMPETENCE_CODAGE,SAMEDI,14,19},
   {1,SPECIALITE_INFORMATIQUE,COMPETENCE_SIGNES,SAMEDI,15,18},
   {2,SPECIALITE_ELECTRICITE,COMPETENCE_SIGNES,MERCREDI,9,11},
   {2,SPECIALITE_CUISINE,COMPETENCE_SIGNES,JEUDI,16,18},
   {2,SPECIALITE_MENUISERIE,COMPETENCE_SIGNES,VENDREDI,10,12},
   {3,SPECIALITE_CUISINE,COMPETENCE_CODAGE,JEUDI,10,12},
   {3,SPECIALITE_MENUISERIE,COMPETENCE_CODAGE,VENDREDI,10,12},
   {3,SPECIALITE_MECANIQUE,COMPETENCE_CODAGE,VENDREDI,9,11},
   {4,SPECIALITE_CUISINE,COMPETENCE_CODAGE,JEUDI,15,19},
   {4,SPECIALITE_MENUISERIE,COMPETENCE_CODAGE,VENDREDI,10,12},
   {4,SPECIALITE_INFORMATIQUE,COMPETENCE_CODAGE,VENDREDI,16,18},
   {5,SPECIALITE_ELECTRICITE,COMPETENCE_SIGNES,MERCREDI,14,19},
   {5,SPECIALITE_ELECTRICITE,COMPETENCE_CODAGE,VENDREDI,16,19},
   {5,SPECIALITE_CUISINE,COMPETENCE_CODAGE,VENDREDI,9,12},
   {6,SPECIALITE_MECANIQUE,COMPETENCE_SIGNES,MARDI,13,18},
   {6,SPECIALITE_CUISINE,COMPETENCE_CODAGE,VENDREDI,15,18},
   {6,SPECIALITE_MECANIQUE,COMPETENCE_CODAGE,MERCREDI,14,18},
   {7,SPECIALITE_INFORMATIQUE,COMPETENCE_CODAGE,VENDREDI,10,12},
   {7,SPECIALITE_MENUISERIE,COMPETENCE_CODAGE,LUNDI,16,19},
   {7,SPECIALITE_MECANIQUE,COMPETENCE_SIGNES,JEUDI,8,10},
   {8,SPECIALITE_MENUISERIE,COMPETENCE_SIGNES,MARDI,15,19},
   {8,SPECIALITE_ELECTRICITE,COMPETENCE_SIGNES,VENDREDI,10,12},
   {8,SPECIALITE_MECANIQUE,COMPETENCE_SIGNES,MARDI,16,19},
   {9,SPECIALITE_ELECTRICITE,COMPETENCE_CODAGE,VENDREDI,9,11},
   {9,SPECIALITE_MECANIQUE,COMPETENCE_CODAGE,LUNDI,10,12},
   {9,SPECIALITE_MECANIQUE,COMPETENCE_SIGNES,MERCREDI,14,16},
   {10,SPECIALITE_MECANIQUE,COMPETENCE_SIGNES,VENDREDI,9,12},
   {10,SPECIALITE_CUISINE,COMPETENCE_SIGNES,MERCREDI,9,11},
   {10,SPECIALITE_INFORMATIQUE,COMPETENCE_SIGNES,VENDREDI,14,17},
   {11,SPECIALITE_MENUISERIE,COMPETENCE_SIGNES,JEUDI,16,18},
   {11,SPECIALITE_INFORMATIQUE,COMPETENCE_SIGNES,MERCREDI,8,12},
   {11,SPECIALITE_MENUISERIE,COMPETENCE_SIGNES,LUNDI,9,12},
   {12,SPECIALITE_MECANIQUE,COMPETENCE_CODAGE,LUNDI,14,17},
   {12,SPECIALITE_MENUISERIE,COMPETENCE_SIGNES,JEUDI,10,12},
   {12,SPECIALITE_ELECTRICITE,COMPETENCE_CODAGE,JEUDI,8,12},
   {13,SPECIALITE_INFORMATIQUE,COMPETENCE_SIGNES,LUNDI,10,12},
   {13,SPECIALITE_MENUISERIE,COMPETENCE_CODAGE,LUNDI,13,15},
   {13,SPECIALITE_ELECTRICITE,COMPETENCE_CODAGE,LUNDI,16,19},
   {14,SPECIALITE_ELECTRICITE,COMPETENCE_CODAGE,VENDREDI,14,17},
   {14,SPECIALITE_CUISINE,COMPETENCE_SIGNES,MERCREDI,13,19},
   {14,SPECIALITE_INFORMATIQUE,COMPETENCE_SIGNES,LUNDI,16,18},
   {15,SPECIALITE_ELECTRICITE,COMPETENCE_SIGNES,JEUDI,10,12},
   {15,SPECIALITE_CUISINE,COMPETENCE_CODAGE,MARDI,14,19},
   {15,SPECIALITE_CUISINE,COMPETENCE_CODAGE,LUNDI,9,12},
   {16,SPECIALITE_INFORMATIQUE,COMPETENCE_CODAGE,VENDREDI,16,18},
   {16,SPECIALITE_INFORMATIQUE,COMPETENCE_SIGNES,JEUDI,9,12},
   {16,SPECIALITE_CUISINE,COMPETENCE_SIGNES,JEUDI,15,19},
   {17,SPECIALITE_ELECTRICITE,COMPETENCE_CODAGE,SAMEDI,15,18},
   {17,SPECIALITE_CUISINE,COMPETENCE_SIGNES,MERCREDI,14,17},
   {17,SPECIALITE_INFORMATIQUE,COMPETENCE_CODAGE,SAMEDI,16,19},
   {18,SPECIALITE_MECANIQUE,COMPETENCE_CODAGE,JEUDI,14,16},
   {18,SPECIALITE_ELECTRICITE,COMPETENCE_CODAGE,MERCREDI,9,11},
   {18,SPECIALITE_INFORMATIQUE,COMPETENCE_SIGNES,MERCREDI,9,11},
   {19,SPECIALITE_MENUISERIE,COMPETENCE_CODAGE,JEUDI,9,11},
   {19,SPECIALITE_INFORMATIQUE,COMPETENCE_SIGNES,VENDREDI,14,17},
   {19,SPECIALITE_MECANIQUE,COMPETENCE_SIGNES,JEUDI,9,12},
   {20,SPECIALITE_INFORMATIQUE,COMPETENCE_CODAGE,JEUDI,13,19},
   {20,SPECIALITE_INFORMATIQUE,COMPETENCE_CODAGE,MARDI,10,12},
   {20,SPECIALITE_INFORMATIQUE,COMPETENCE_CODAGE,MARDI,8,11},
   {21,SPECIALITE_INFORMATIQUE,COMPETENCE_SIGNES,JEUDI,8,11},
   {21,SPECIALITE_MECANIQUE,COMPETENCE_CODAGE,MARDI,8,12},
   {21,SPECIALITE_CUISINE,COMPETENCE_CODAGE,JEUDI,9,11},
   {22,SPECIALITE_MECANIQUE,COMPETENCE_SIGNES,VENDREDI,10,12},
   {22,SPECIALITE_MECANIQUE,COMPETENCE_SIGNES,MERCREDI,8,11},
   {22,SPECIALITE_MENUISERIE,COMPETENCE_CODAGE,VENDREDI,14,19},
   {23,SPECIALITE_MENUISERIE,COMPETENCE_CODAGE,MERCREDI,10,12},
   {23,SPECIALITE_MECANIQUE,COMPETENCE_CODAGE,LUNDI,14,16},
   {23,SPECIALITE_ELECTRICITE,COMPETENCE_CODAGE,VENDREDI,15,19},
   {24,SPECIALITE_ELECTRICITE,COMPETENCE_SIGNES,MARDI,10,12},
   {24,SPECIALITE_MENUISERIE,COMPETENCE_SIGNES,MARDI,16,19},
   {24,SPECIALITE_CUISINE,COMPETENCE_SIGNES,SAMEDI,13,18},
   {25,SPECIALITE_MENUISERIE,COMPETENCE_SIGNES,MERCREDI,15,18},
   {25,SPECIALITE_INFORMATIQUE,COMPETENCE_SIGNES,MARDI,9,11},
   {25,SPECIALITE_MECANIQUE,COMPETENCE_CODAGE,VENDREDI,14,18},
   {26,SPECIALITE_CUISINE,COMPETENCE_CODAGE,MERCREDI,9,11},
   {26,SPECIALITE_ELECTRICITE,COMPETENCE_CODAGE,MARDI,15,19},
   {26,SPECIALITE_ELECTRICITE,COMPETENCE_SIGNES,JEUDI,14,19},
   {27,SPECIALITE_CUISINE,COMPETENCE_CODAGE,MARDI,9,12},
   {27,SPECIALITE_ELECTRICITE,COMPETENCE_SIGNES,VENDREDI,13,19},
   {27,SPECIALITE_MECANIQUE,COMPETENCE_CODAGE,LUNDI,15,17},
   {28,SPECIALITE_MENUISERIE,COMPETENCE_CODAGE,SAMEDI,14,18},
   {28,SPECIALITE_INFORMATIQUE,COMPETENCE_SIGNES,SAMEDI,9,11},
   {28,SPECIALITE_MECANIQUE,COMPETENCE_SIGNES,SAMEDI,8,12},
   {29,SPECIALITE_ELECTRICITE,COMPETENCE_SIGNES,MERCREDI,14,16},
   {29,SPECIALITE_ELECTRICITE,COMPETENCE_SIGNES,LUNDI,8,10},
   {29,SPECIALITE_MECANIQUE,COMPETENCE_CODAGE,MARDI,15,17},
   {30,SPECIALITE_INFORMATIQUE,COMPETENCE_CODAGE,VENDREDI,14,16},
   {30,SPECIALITE_INFORMATIQUE,COMPETENCE_CODAGE,JEUDI,16,19},
   {30,SPECIALITE_MECANIQUE,COMPETENCE_SIGNES,LUNDI,8,11},
   {31,SPECIALITE_INFORMATIQUE,COMPETENCE_SIGNES,MERCREDI,14,19},
   {31,SPECIALITE_MECANIQUE,COMPETENCE_CODAGE,SAMEDI,10,12},
   {31,SPECIALITE_MENUISERIE,COMPETENCE_CODAGE,LUNDI,14,17}
};
                  
// EOF
